### ISSUE TITLE
Troubleshooting section

### ISSUE THREAD

**Issue by lyndhurst** [borgbase/docs.borgbase.com#20]
Hi,

I am sorry if this is not the right place, but I cannot find an answer on docs.borgbase.com, and the doc does not have a common error that relates to my problem.

I am stuck with an error, and everything I find on the internet points to solutions to implement on the server side; the error message points to a server side error too.

I have  no idea where to turn to try and solve it. I do have a few simple ssh keys setup like github for example that works well.

I created an ssh key pair, copied the public key on my borgbase account, so far everythnig seems to be ok.

```bash
$ borg init -e repokey-blake2 ssh://xxx@xxx.repo.borgbase.com/./repo

Remote: xxx@xxx.repo.borgbase.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Connection closed by remote host. Is borg working on the server?
```

I tried to change the borg version on my account to make sure it matches the one installed on my laptop.
My ssh config is as follows but I tried many changes there for consistently the same error message:

```config
Host *
  AddKeysToAgent yes
  IgnoreUnknown UseKeychain
  UseKeychain yes

Host borgbase
  HostName xxx.repo.borgbase.com
  User xxx
  IdentityFile ~/.ssh/borgbase
  IdentitiesOnly yes
```

Any help would be greatly appreciated, thanks in advance.

**Comment by m3nu** [comment]
Hi,

this sounds more like a support request. So I suggest to first look at our [FAQ](https://docs.borgbase.com/faq/#all-connections-to-a-borgbase-repo-fail-with-an-error-immediately) (has the most common solutions for this problem) and then drop an email to `hello (at) borgbase.com`, where someone can assist.

**Comment by lyndhurst** [comment]
There are actually a troubleshooting section, sorry, when I was clicking I only saw a dropdown with a subsection "create a key pair", I missed  he actual page. Thank you.
